version: '3'
services:
  psql:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: tigernotes
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app-ktor:
    image: tn-app-ktor:0.0.1
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      PG_URL: jdbc:postgresql://psql:5432/tigernotes
      PG_USER: postgres
      PG_PASSWORD: password
      PG_SCHEMA: tigernotes
    depends_on:
      psql:
        condition: service_healthy

volumes:
  postgres_data:

