openapi: 3.0.4
info:
  title: Tigernotes log models
  description: Log models for logging services of tigernotes
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
paths: {}

components:
  schemas:
    CommonLogModel:
      title: Общая модель лога
      description: Общая модель лога для всех микросервисов системы
      type: object
      properties:
        messageTime:
          type: string
        logId:
          type: string
        source:
          type: string
        note:
          $ref: '#/components/schemas/TnLogModel'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorLogModel'

    TnLogModel:
      title: Модель лога для микросервиса Tigernotes
      type: object
      properties:
        requestId:
          type: string
        operation:
          type: string
          enum:
            - create
            - read
            - update
            - delete
            - search
        requestNote:
          $ref: '#/components/schemas/NoteLog'
        requestFilter:
          $ref: '#/components/schemas/NoteFilterLog'
        responseNote:
          $ref: '#/components/schemas/NoteLog'
        responseNotes:
          type: array
          items:
            $ref: '#/components/schemas/NoteLog'

    ErrorLogModel:
      title: Модель лога для ошибки
      type: object
      properties:
        message:
          type: string
        field:
          type: string
        code:
          type: string
        level:
          type: string

    NoteLog:
      title: Модель лога для объявления
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        timeCreate:
          type: string
        email:
          type: string
        timeReminder:
          type: string

    NoteFilterLog:
      title: Модель лога фильтра
      properties:
        searchTitle:
          type: string
        dateStart:
          type: string
        dateEnd:
          type: string

